### ISSUE TITLE
how do you install this?

### ISSUE THREAD

**Issue by mreassassin** [Schamper/xbox-remote-power#35]
I can't get the xbox to show up in homeassistant.  how do you install this?  i tried:

pip install xbox-remote-power

and got:

(homeassistant) homeassistant@raspberrypi:/srv/homeassistant $ pip install xbox-remote-power
Collecting xbox-remote-power
  Could not find a version that satisfies the requirement xbox-remote-power (from versions: )
No matching distribution found for xbox-remote-power

thanks for any help!!

**Comment by spinside** [comment]
You need to download the files to your local machine.
Use git clone.
```
git clone https://github.com/Schamper/xbox-remote-power.git
```
Now you will have a new folder called "xbox-remote-power" with the script. Change directory to the xbox-remote-power directory.
Now you can use the following command to run the script:
```
python xbox-remote-power.py -a <ip address> -i <live id>
```
The script can be added to Homeassistant as follows:

```
switch:
  - platform: command_line
    switches:
      xbox:
        command_on: python /srv/homeassistant/xbox-remote-power/xbox-remote-power.py -a <ip address> -i <live id>
        command_off: python /srv/homeassistant/xbox-remote-power/xbox-remote-power.py -a <ip address> -i <live id>
```
